### ISSUE TITLE
Get Bone positions from FBX file

### ISSUE THREAD

**Issue by JBVAkshaya** [owl-project/NVISII#102]
Is there a way to extract bone positions from a skeletal mesh FDX file using this library? I am trying to create a dataset for a robotic arm as done in the DREAM project using NDDS.

**Comment by n8vm** [comment]
Hey @JBVAkshaya,

We don’t natively support bones or skin weights at the moment. TBH, I’m not entirely sure what a FBX skeletal mesh is. We do have that data importing internally, but I don’t use it yet in nvisii.

Do skeletal meshes require skin weights? Or does the skeleton just define a hierarchy of meshes and corresponding transforms?

**Comment by n8vm** [comment]
Ah, yeah, a bone hierarchy in Blender defines a mechanism to deform a triangular mesh using corresponding skinned weight masks per joint. Bone hierarchies by themselves cannot be rendered directly, since they do not define geometry by themselves. If a bone hierarchy is being used to deform different parts of a mesh, that would imply there's some skinning going on, which we unfortunately don't support at the moment.

Your later question is orthogonal to the question on support for FBX joints. @jontremblay can probably help you out if you open a separate issue that's specific to NDDS.
