### ISSUE TITLE
optical flow

### ISSUE THREAD

**Issue by Acnext** [owl-project/NVISII#111]
I want to generate optical flow as gt and  If object is with reflective materials in our scene， can l get optical flow data？

**Comment by TontonTremblay** [comment]
do you mean you want the movement perceived in the reflective object? I am afraid that is not possible right now.

**Comment by n8vm** [comment]
Jonathan is correct, motion vectors for virtual reflected images is not supported (and is one of the on-going research challenges in modern ray tracer denoising!)

One thing you might consider is using a post-process optical flow estimator like the one here: https://developer.nvidia.com/opticalflow-sdk

Closing this issue though, since we do not have any immediate plans to support specular motion vectors.
