### ISSUE TITLE
Is there any way to generate optical flow from motion vector?

### ISSUE THREAD

**Issue by YWQQQQQQ** [owl-project/NVISII#138]
Example "20.motion_vectors.py" renders and visualizes a 4-dim motion vector but what's the meaning of each dimension in motion vector? I couldn't find it in documents and tutorial. Is there any way to generate 2-dim optical flow (horizontal flow & vertical flow) from motion vector? Thanks!

**Comment by natevm** [comment]
Our motion vectors are the same type of motion vectors used my TAA or DLSS. They are returned as vec4s because most image formats expect four channels, but you only need to read the first two channels with motion vectors. These first two values indicate the motion of the object in normalized screen space. In the motion blur example you brought up, we scale those motion vectors to account for resolution, and then use those motion vectors to lookup object locations in the previous frame, as well as to detect disocclusions.

**Comment by TontonTremblay** [comment]
You can ignore the last dimension. You get a 3d vector with the first 3 values, e.g., `[x,y,z]`. The example shows the 3d vectors projected in color plane.
