### ISSUE TITLE
Will restir branch get merged to master

### ISSUE THREAD

**Issue by diwot** [owl-project/NVISII#143]
Hi
I noticed that there is a branch that seems to implement restir (according to the branch name, actually I have not tested it). Since restir can help to speed up convergence of path traced scenes a lot, I was wondering if there are plans to bring that functionality to master. I don't think it is on master since all content in the file https://github.com/owl-project/NVISII/blob/master/src/nvisii/devicecode/reservoir.h is commented out.
![image](https://user-images.githubusercontent.com/45295576/158154177-0abe389c-cbf2-4dbb-8cfd-a06a50304e1f.png)
Great project by the way :)

**Comment by natevm** [comment]
Hey diwot, thanks for the interest!

restir is complicated. It’s mainly useful for games, and works by iteratively optimizing for the perfect single representative sample, sharing those results over space and time. In games, that’s what you want, since you then apply a denoiser to filter out any remaining noise. 

However, ReSTIR does not converge to the true ground truth. For example, if two lights equally light a surface, a ReSTIR reservoir will get stuck with either one light or the other, and cannot simultaneously account for the contributions of both lights. So, at least as far as I know, you cannot use ReSTIR to render unbiased high quality images. 

Perhaps one day we’ll make an approximate real-time rendering mode to nvisii. But for now, I’d instead prefer to improve how we importance sample lights, to somehow account for distance in addition to luminance.
